name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x' 

      - name: Restore dependencies
        run: |
          cd patient-management-backend  
          dotnet restore

      - name: Build
        run: |
          cd patient-management-backend 
          dotnet build --configuration Release

      - name: Publish
        run: |
          cd patient-management-backend  
          dotnet publish --configuration Release --output ./publish

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: './patient-management-backend/publish'
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: |
          cd patient-management-frontend
          npm install

      - name: Build frontend
        run: |
          cd patient-management-frontend
          npm run build

      - name: Deploy frontend
        run: |
          cd patient-management-frontend
          npm run deploy
