name: Build and Deploy API

on:
  workflow_dispatch:

env:  
  AZURE_WEB_APP: "PatientManagement"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: dotnet restore ./patient-management-backend/PatientManagementApi.csproj

      - name: Build
        run: dotnet build ./patient-management-backend/PatientManagementApi.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./patient-management-backend/PatientManagementApi.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: './publish'
