name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Restore dependencies
        run: |
          cd patient-management-backend  
          dotnet restore

      - name: Build
        run: |
          cd patient-management-backend 
          dotnet build --configuration Release

      - name: Publish
        run: |
          cd patient-management-backend  
          dotnet publish --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.FRONTEND_AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.FRONTEND_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './publish'
